### ISSUE TITLE
OSM tag `maxspeed` can have non-numeric values

### ISSUE THREAD

**Issue by christophfink** [DigitalGeographyLab/Helsinki-Travel-Time-Matrices#30]
```
Traceback (most recent call last):
  File "/home/dgl/.local/bin/travel-time-matrix", line 8, in <module>
    sys.exit(main())
  File "/home/dgl/.local/lib/python3.10/site-packages/travel_time_matrix_computer/__main__.py", line 130, in main
    travel_times = travel_time_matrix_computer.run()
  File "/home/dgl/.local/lib/python3.10/site-packages/travel_time_matrix_computer/travel_time_matrix_computer.py", line 40, in run
    travel_times = travel_times.join(car_travel_time_matrix_computer.run())
  File "/home/dgl/.local/lib/python3.10/site-packages/travel_time_matrix_computer/car_travel_time_matrix_computer.py", line 66, in run
    car_speed_annotator.CarSpeedAnnotator(timeslot_name).annotate(
  File "/home/dgl/.local/lib/python3.10/site-packages/car_speed_annotator/car_speed_annotator.py", line 148, in annotate
    self.apply_file(str(input_file))
  File "/home/dgl/.local/lib/python3.10/site-packages/car_speed_annotator/car_speed_annotator.py", line 164, in way
    speed_limit = self._get_speed_limit(tags)
  File "/home/dgl/.local/lib/python3.10/site-packages/car_speed_annotator/car_speed_annotator.py", line 234, in _get_speed_limit
    speed_limit = int(tags["maxspeed"])
ValueError: invalid literal for int() with base 10: 'walk'
```

**Comment by christophfink** [comment]
cf. https://wiki.openstreetmap.org/wiki/Key:maxspeed
